data_crawler_task:
  description: >
    Given {date}, crawl the data from the webpage.
  expected_output: >
    Crawled data saved directly from the tool.

data_engineer_task:
  description: >
    Given {date}, fetch the data from the given location, store them in a vector store,
  expected_output: >
    Given date, all the news data is stored properly for that date,

data_analyst_task:
  description: >
    Given {date}, summarize all the important retrieved news data from the date, and fetch the summary as a news reporter.
  expected_output: >
    Show the concise retrieved news summary in the fashion of a news reporter to describe.

speaker_task:
  description: >
    given the full news report text, speaker convert the text to audio mp3, and play the audio file
  expected_output: >
    The tool plays the saved audio file